import { createClient } from 'npm:@supabase/supabase-js@2.95.0'

const OWNER='bonebrakewebsitedesign@gmail.com'
const FALLBACK_A='76.76.21.21'
const FALLBACK_CNAME='cname.vercel-dns-0.com'
const now=()=>new Date().toISOString()
const clean=(v:unknown,max=1000)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)
async function sha256(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function sameSecret(a:string,b:string){if(!a||!b)return false;const[x,y]=await Promise.all([sha256(a),sha256(b)]);return x===y}
function randomToken(){const b=crypto.getRandomValues(new Uint8Array(32));return Array.from(b).map(x=>x.toString(16).padStart(2,'0')).join('')}
function cors(req:Request){const o=req.headers.get('origin')||'';const ok=o==='https://bwdnorth.com'||o==='https://www.bwdnorth.com'||/^https:\/\/[-a-z0-9]+\.vercel\.app$/i.test(o);return{'Access-Control-Allow-Origin':ok?o:'https://bwdnorth.com','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-bonebrake-domain-key','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin','Cache-Control':'no-store'}}
function normalizeHost(input:string){let v=clean(input,500).toLowerCase();if(!v)throw new Error('hostname_required');try{v=new URL(v.includes('://')?v:`https://${v}`).hostname.toLowerCase()}catch{throw new Error('invalid_hostname')}v=v.replace(/\.$/,'');if(v==='localhost'||/^\d{1,3}(?:\.\d{1,3}){3}$/.test(v)||!v.includes('.')||v.length>253||!/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$/.test(v))throw new Error('public_domain_required');return v}
async function dns(name:string,type:string){const r=await fetch(`https://dns.google/resolve?name=${encodeURIComponent(name)}&type=${encodeURIComponent(type)}`,{headers:{Accept:'application/dns-json'},signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error(`dns_http_${r.status}`);return await r.json()}
function answers(d:any,type:number){return(Array.isArray(d?.Answer)?d.Answer:[]).filter((x:any)=>Number(x.type)===type).map((x:any)=>String(x.data||'').replace(/^"|"$/g,'').replace(/\.$/,'').toLowerCase())}
async function findZone(host:string){const labels=host.split('.');for(let i=0;i<=Math.max(0,labels.length-2);i++){const c=labels.slice(i).join('.');try{const d=await dns(c,'SOA');if(Array.isArray(d?.Answer)&&d.Answer.some((x:any)=>Number(x.type)===6))return c}catch{}}return labels.slice(-2).join('.')}
function fallbackRecord(host:string,zone:string){if(host===zone)return{type:'A',name:'@',value:FALLBACK_A,hostname:host,purpose:'routing'};const name=host.endsWith(`.${zone}`)?host.slice(0,-1-zone.length):host;return{type:'CNAME',name,value:FALLBACK_CNAME,hostname:host,purpose:'routing'}}
function fqdn(req:any,zone:string,host:string){const n=clean(req?.hostname||req?.name||'',500).toLowerCase();if(!n||n==='@')return zone||host;if(n===host||n.endsWith(`.${zone}`))return n;return `${n}.${zone}`}
async function inspectRequirement(req:any,zone:string,host:string){const type=clean(req?.type,20).toUpperCase(),name=fqdn(req,zone,host),expected=String(req?.value||'').replace(/^"|"$/g,'').replace(/\.$/,'').toLowerCase();if(!['A','CNAME','TXT'].includes(type)||!expected)return{ready:false,type,name,expected,observed:[],error:'unsupported_or_empty_requirement'};const d=await dns(name,type),code=type==='A'?1:type==='CNAME'?5:16,seen=answers(d,code);return{ready:seen.includes(expected),type,name,expected,observed:seen,status:d?.Status??null}}
async function inspectDns(row:any){const reqs=Array.isArray(row.dns_requirements)?row.dns_requirements:[];if(row.dns_instructions_authoritative&&reqs.length){const results=[];for(const r of reqs){try{results.push(await inspectRequirement(r,row.domain_zone||row.hostname,row.hostname))}catch(error){results.push({ready:false,error:clean(error instanceof Error?error.message:String(error),300),type:r?.type,name:r?.name})}}return{ready:results.every((x:any)=>x.ready===true),authoritative:true,requirements:results}}
 const provisional={type:row.dns_record_type,name:row.dns_record_name,value:row.dns_record_value,hostname:row.hostname};let diagnostic:any=null;try{diagnostic=await inspectRequirement(provisional,row.domain_zone||row.hostname,row.hostname)}catch(error){diagnostic={ready:false,error:clean(error instanceof Error?error.message:String(error),300)}}return{ready:false,authoritative:false,reason:'awaiting_authoritative_vercel_dns',provisional:diagnostic}}
async function httpsCheck(host:string){try{const r=await fetch(`https://${host}/`,{method:'GET',redirect:'manual',signal:AbortSignal.timeout(9000),headers:{'User-Agent':'Bonebrake-Domain-Health/14.0'}});return{ready:true,status:r.status}}catch(error){return{ready:false,status:null,error:clean(error instanceof Error?error.message:String(error),500)}}}

Deno.serve(async(req:Request)=>{
 const headers=cors(req);if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return Response.json({ok:false,error:'method_not_allowed'},{status:405,headers})
 const sb=Deno.env.get('SUPABASE_URL'),service=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}')['default'];if(!sb||!service)return Response.json({ok:false,error:'server_configuration_error'},{status:500,headers});const db=createClient(sb,service,{auth:{persistSession:false,autoRefreshToken:false}});let body:any={};try{body=await req.json()}catch{}
 const action=clean(body?.action||'check',40);const[{data:stored},{data:settings}]=await Promise.all([db.from('integration_secrets').select('secret_value').eq('key','domain_onboarding_worker_secret').maybeSingle(),db.from('automation_settings').select('*').eq('key','global').maybeSingle()]);if(!settings)return Response.json({ok:false,error:'settings_unavailable'},{status:503,headers})
 const worker=await sameSecret(req.headers.get('x-bonebrake-domain-key')||'',String(stored?.secret_value||''));let owner=false;const auth=req.headers.get('authorization')||'',jwt=auth.startsWith('Bearer ')?auth.slice(7):'';if(jwt){const{data:{user}}=await db.auth.getUser(jwt);owner=String(user?.email||'').toLowerCase()===OWNER}
 let tokenRow:any=null;const t=clean(body?.token||'',200);if(!owner&&!worker&&t){const h=await sha256(t);const{data}=await db.from('project_site_domains').select('*').eq('setup_token_hash',h).gt('setup_token_expires_at',now()).maybeSingle();tokenRow=data||null}
 const event=async(row:any,event_type:string,source:string,detail:any={})=>{await db.from('domain_onboarding_events').insert({domain_id:row.id,project_id:row.project_id,event_type,source,detail})}
 const checkOne=async(row:any,source:string)=>{const dnsState=await inspectDns(row);const dnsReady=dnsState.authoritative&&dnsState.ready;let ssl=row.ssl_status==='ready'?'ready':'pending',https:any={ready:false,status:null};if(dnsReady&&row.host_status==='attached'){https=await httpsCheck(row.hostname);ssl=https.ready?'ready':'pending'}let status=row.status;if(!['active','disabled'].includes(row.status)){if(row.host_status==='error')status='error';else if(row.host_status==='attached'&&dnsReady&&ssl==='ready')status='verified';else if(['attached','verification_required'].includes(row.host_status))status='awaiting_dns';else status='pending'}const stamp=now(),patch:any={dns_status:dnsReady?'ready':'pending',dns_observed:dnsState,dns_checked_at:stamp,last_checked_at:stamp,check_count:Number(row.check_count||0)+1,ssl_status:row.host_status==='error'?'error':ssl,last_https_status:https.status??null,status,updated_at:stamp};if(dnsReady&&!row.dns_ready_at)patch.dns_ready_at=stamp;if(status==='verified'&&!row.verified_at)patch.verified_at=stamp;if(ssl==='ready'&&!row.ssl_ready_at)patch.ssl_ready_at=stamp;if(status==='verified'&&ssl==='ready'&&!row.onboarding_completed_at)patch.onboarding_completed_at=stamp;const{data:updated,error}=await db.from('project_site_domains').update(patch).eq('id',row.id).select('*').single();if(error)throw error;await event(updated,'domain_checked',source,{authoritative:dnsState.authoritative,dns_ready:dnsReady,host_status:row.host_status,ssl_ready:ssl==='ready',https_status:https.status??null});return updated}
 if(action==='register'){
  if(!owner)return Response.json({ok:false,error:'owner_auth_required'},{status:401,headers});if(!settings.domain_onboarding_enabled)return Response.json({ok:false,error:'domain_onboarding_disabled'},{status:409,headers});let host='';try{host=normalizeHost(body?.hostname)}catch(error){return Response.json({ok:false,error:error instanceof Error?error.message:'invalid_hostname'},{status:400,headers})}const projectId=clean(body?.project_id,80);const{data:p}=await db.from('projects').select('id,client_name,status').eq('id',projectId).maybeSingle();if(!p||p.status==='cancelled')return Response.json({ok:false,error:'active_project_required'},{status:404,headers});const{data:existing}=await db.from('project_site_domains').select('*').eq('hostname',host).maybeSingle();if(existing&&existing.project_id!==projectId)return Response.json({ok:false,error:'domain_already_assigned'},{status:409,headers});let zone=host;try{zone=await findZone(host)}catch{}const provisional=fallbackRecord(host,zone),raw=randomToken(),hash=await sha256(raw),expires=new Date(Date.now()+30*86400_000).toISOString(),stamp=now();const values:any={project_id:projectId,hostname:host,is_primary:body?.is_primary!==false,status:'pending',ssl_status:'unknown',domain_zone:zone,domain_kind:host===zone?'apex':'subdomain',dns_status:'pending',host_status:'approval_pending',dns_record_type:provisional.type,dns_record_name:provisional.name,dns_record_value:provisional.value,dns_requirements:[],dns_instructions_authoritative:false,verification_method:'vercel_project_domain+dns+tls',verification_data:{host_project_id:settings.vercel_host_project_id,team_id:settings.vercel_team_id,provisional_dns:provisional,dns_instruction_state:'awaiting_vercel'},host_project_id:settings.vercel_host_project_id,setup_token_hash:hash,setup_token_expires_at:expires,updated_at:stamp};let row:any;if(existing){const{data,error}=await db.from('project_site_domains').update(values).eq('id',existing.id).select('*').single();if(error)return Response.json({ok:false,error:'domain_update_failed',detail:clean(error.message,500)},{status:409,headers});row=data}else{const{data,error}=await db.from('project_site_domains').insert(values).select('*').single();if(error)return Response.json({ok:false,error:'domain_create_failed',detail:clean(error.message,500)},{status:409,headers});row=data}await db.from('projects').update({domain_status:'waiting',updated_at:stamp}).eq('id',projectId)
  const{data:open}=await db.from('automation_actions').select('id').eq('action_type','attach_client_domain_to_vercel').eq('entity_type','project').eq('entity_id',projectId).in('status',['pending','approved','executing']).limit(1);let actionId=open?.[0]?.id||null;if(!actionId){const{data:a}=await db.from('automation_actions').insert({action_type:'attach_client_domain_to_vercel',entity_type:'project',entity_id:projectId,title:`Attach ${host} to Bonebrake hosting`,summary:'Register this client domain on the canonical Bonebrake Vercel host and retrieve authoritative verification/DNS requirements. External hosting configuration requires owner approval.',risk_level:'approval',status:'pending',proposed_by:'domain_onboarding',payload:{project_id:projectId,domain_id:row.id,hostname:host,vercel_project_id:settings.vercel_host_project_id,vercel_project_name:settings.vercel_host_project_name,vercel_team_id:settings.vercel_team_id,external_effect:'vercel_project_domain_attachment'}}).select('id').single();actionId=a?.id||null}await event(row,'domain_registered','owner',{hostname:host,zone,attach_action_id:actionId,dns_instruction_state:'awaiting_vercel'});return Response.json({ok:true,domain:row,attach_action_id:actionId,dns_instruction_state:'waiting_for_vercel',setup_url:`https://bwdnorth.com/client-domain.html?token=${raw}`,setup_token_expires_at:expires},{headers})
 }
 if(action==='rotate_token'){if(!owner)return Response.json({ok:false,error:'owner_auth_required'},{status:401,headers});const raw=randomToken(),hash=await sha256(raw),expires=new Date(Date.now()+30*86400_000).toISOString();const{data:row,error}=await db.from('project_site_domains').update({setup_token_hash:hash,setup_token_expires_at:expires,updated_at:now()}).eq('id',clean(body?.domain_id,80)).select('*').maybeSingle();if(error||!row)return Response.json({ok:false,error:'domain_not_found'},{status:404,headers});await event(row,'setup_token_rotated','owner',{});return Response.json({ok:true,setup_url:`https://bwdnorth.com/client-domain.html?token=${raw}`,setup_token_expires_at:expires},{headers})}
 if(action==='sweep'){if(!worker)return Response.json({ok:false,error:'domain_worker_auth_required'},{status:401,headers});if(!settings.domain_onboarding_enabled)return Response.json({ok:true,status:'skipped',reason:'domain_onboarding_disabled'},{headers});const{data:rows}=await db.from('project_site_domains').select('*').not('status','in','("active","disabled")').order('last_checked_at',{ascending:true,nullsFirst:true}).limit(20);const out=[];for(const r of rows||[]){try{const u=await checkOne(r,'scheduler');out.push({id:u.id,status:u.status,dns_status:u.dns_status,host_status:u.host_status,ssl_status:u.ssl_status})}catch(error){out.push({id:r.id,error:clean(error instanceof Error?error.message:String(error),300)})}}return Response.json({ok:true,checked:out.length,domains:out},{headers})}
 if(action==='check'){let row:any=tokenRow;if(!row&&(owner||worker)){const id=clean(body?.domain_id,80);if(id){const{data}=await db.from('project_site_domains').select('*').eq('id',id).maybeSingle();row=data}else if(body?.hostname){let h='';try{h=normalizeHost(body.hostname)}catch{}if(h){const{data}=await db.from('project_site_domains').select('*').eq('hostname',h).maybeSingle();row=data}}}if(!row)return Response.json({ok:false,error:'domain_auth_or_record_required'},{status:401,headers});try{const u=await checkOne(row,tokenRow?'client':worker?'scheduler':'owner');return Response.json({ok:true,domain:{id:u.id,project_id:u.project_id,hostname:u.hostname,status:u.status,dns_status:u.dns_status,host_status:u.host_status,ssl_status:u.ssl_status,dns_instructions_authoritative:u.dns_instructions_authoritative,dns_requirements:u.dns_requirements,dns_observed:u.dns_observed,dns_checked_at:u.dns_checked_at,verified_at:u.verified_at,ssl_ready_at:u.ssl_ready_at,onboarding_completed_at:u.onboarding_completed_at}}, {headers})}catch(error){return Response.json({ok:false,error:'domain_check_failed',detail:clean(error instanceof Error?error.message:String(error),500)},{status:500,headers})}}
 if(action==='status'){let row:any=tokenRow;if(!row&&owner){const{data}=await db.from('project_site_domains').select('*').eq('id',clean(body?.domain_id,80)).maybeSingle();row=data}if(!row)return Response.json({ok:false,error:'domain_auth_or_record_required'},{status:401,headers});return Response.json({ok:true,domain:{id:row.id,project_id:row.project_id,hostname:row.hostname,status:row.status,dns_status:row.dns_status,host_status:row.host_status,ssl_status:row.ssl_status,dns_instructions_authoritative:row.dns_instructions_authoritative,dns_requirements:row.dns_requirements,dns_observed:row.dns_observed,dns_checked_at:row.dns_checked_at,verified_at:row.verified_at,ssl_ready_at:row.ssl_ready_at,onboarding_completed_at:row.onboarding_completed_at,setup_token_expires_at:row.setup_token_expires_at}}, {headers})}
 return Response.json({ok:false,error:'unsupported_action'},{status:400,headers})
})