(()=>{
const SB='https://usurytofnhhfxxipngdd.supabase.co';const KEY='sb_publishable_jpA7u89wOaxWcyO5NU5cGw_HkQTnOkv';const LEAD=`${SB}/functions/v1/lead-intake`;const TRACK=`${SB}/functions/v1/analytics-track`;
const css=document.createElement('link');css.rel='stylesheet';css.href='phase11.css';document.head.appendChild(css);
if(!document.querySelector('.skip-link')){const skip=document.createElement('a');skip.className='skip-link';skip.href='#top';skip.textContent='Skip to content';document.body.prepend(skip)}
const nav=document.querySelector('.site-nav');const menu=document.querySelector('.menu-toggle');const panel=document.querySelector('.mobile-panel');const progress=document.querySelector('.scroll-progress span');
function onScroll(){if(nav)nav.classList.toggle('scrolled',scrollY>18);if(progress){const d=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${d>0?scrollY/d:0})`;}}
addEventListener('scroll',onScroll,{passive:true});onScroll();
function addAuditNavigation(){const desktop=document.querySelector('.nav-links');if(desktop&&!desktop.querySelector('[href="website-audit.html"]')){const a=document.createElement('a');a.href='website-audit.html';a.className='p11-audit-link';a.textContent='Audit';desktop.appendChild(a)}const mobile=panel?.querySelector('nav');if(mobile&&!mobile.querySelector('[href="website-audit.html"]')){const a=document.createElement('a');a.href='website-audit.html';a.className='p11-audit-link';a.textContent='Free website audit';mobile.insertBefore(a,mobile.querySelector('[href="#contact"]')||null)}const actions=document.querySelector('.hero-actions');if(actions&&!actions.querySelector('[href="website-audit.html"]')){const a=document.createElement('a');a.href='website-audit.html';a.className='btn btn-outline-light p11-hero-audit';a.textContent='Run free website audit';actions.appendChild(a)}if(!document.querySelector('.p11-mobile-action')){const bar=document.createElement('div');bar.className='p11-mobile-action';bar.innerHTML='<a href="tel:+13312033717">Call</a><a href="website-audit.html">Free audit</a><a href="#contact">Start project</a>';document.body.appendChild(bar)}}addAuditNavigation();
if(menu&&panel){menu.addEventListener('click',()=>{const open=!panel.classList.contains('open');panel.classList.toggle('open',open);menu.classList.toggle('open',open);document.body.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',String(open));});panel.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{panel.classList.remove('open');menu.classList.remove('open');document.body.classList.remove('menu-open');menu.setAttribute('aria-expanded','false');}));}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced&&'IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));}else document.querySelectorAll('.reveal').forEach(el=>el.classList.add('in'));
document.querySelectorAll('.faq-q').forEach(b=>{b.setAttribute('aria-expanded',String(b.closest('.faq-item')?.classList.contains('open')));b.addEventListener('click',()=>{const item=b.closest('.faq-item');const open=!item.classList.contains('open');item.classList.toggle('open',open);b.setAttribute('aria-expanded',String(open))})});
let session=localStorage.getItem('bwd_session_id');if(!session){session=crypto.randomUUID();localStorage.setItem('bwd_session_id',session)}const qs=new URLSearchParams(location.search);const attr={utm_source:qs.get('utm_source')||'',utm_medium:qs.get('utm_medium')||'',utm_campaign:qs.get('utm_campaign')||'',utm_content:qs.get('utm_content')||'',utm_term:qs.get('utm_term')||'',referrer:document.referrer||''};
async function track(event_type,metadata={}){try{await fetch(TRACK,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({session_id:session,event_type,path:location.pathname,source:attr.utm_source,medium:attr.utm_medium,campaign:attr.utm_campaign,referrer:attr.referrer,metadata}),keepalive:true})}catch{}}
track('page_view',{title:document.title});document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;if(a.matches('.btn,.nav-cta,.nav-phone,.text-link,.p11-mobile-action a'))track('cta_click',{label:(a.textContent||'').trim().slice(0,80),href:(a.getAttribute('href')||'').slice(0,300)})},{passive:true});
async function loadCms(){try{const res=await fetch(`${SB}/rest/v1/content_items?select=type,slug,title,payload&published=eq.true`,{headers:{apikey:KEY}});if(!res.ok)return;const items=await res.json();for(const item of items){if(item.slug==='pricing-packages'&&Array.isArray(item.payload?.packages)){document.querySelectorAll('.price-card').forEach((card,i)=>{const p=item.payload.packages[i];if(!p)return;const h=card.querySelector('h3');if(h&&p.price){const text=[...h.childNodes].find(n=>n.nodeType===Node.TEXT_NODE);if(text)text.nodeValue=p.price;else h.prepend(document.createTextNode(p.price))}const intro=card.querySelector('.intro');if(intro&&p.description)intro.textContent=p.description})}if(item.slug==='faq-core'&&Array.isArray(item.payload?.items)){document.querySelectorAll('.faq-item').forEach((row,i)=>{const f=item.payload.items[i];if(!f)return;const q=row.querySelector('.faq-q');const p=row.querySelector('.faq-a p');if(q&&f.question){const icon=q.querySelector('i');q.textContent=f.question;if(icon)q.appendChild(icon)}if(p&&f.answer)p.textContent=f.answer})}if(item.slug==='business-profile'){const phone=item.payload?.phone,email=item.payload?.email;if(phone)document.querySelectorAll('a[href^="tel:"]').forEach(a=>{a.href=`tel:+1${String(phone).replace(/\D/g,'')}`;if(a.textContent.trim().match(/\d/))a.textContent=phone});if(email)document.querySelectorAll('a[href^="mailto:"]').forEach(a=>{a.href=`mailto:${email}`;if(a.textContent.includes('@'))a.textContent=email})}}}catch(err){console.warn('cms_read_failed')}}loadCms();
const form=document.querySelector('#contactForm');
function enrichForm(){if(!form)return;const grid=form.querySelector('.form-grid');const desc=grid?.querySelector('.field.full');if(grid&&desc&&!form.querySelector('#company')){const company=document.createElement('div');company.className='field';company.innerHTML='<label for="company">Company / business</label><input id="company" name="company" type="text" autocomplete="organization" placeholder="Business name">';const budget=document.createElement('div');budget.className='field';budget.innerHTML='<label for="budget">Approximate budget</label><select id="budget" name="budget"><option value="">Not sure yet</option><option>$1,250–$2,000</option><option>$2,000–$3,500</option><option>$3,500–$5,000</option><option>$5,000+</option></select>';grid.insertBefore(company,desc);grid.insertBefore(budget,desc)}if(!form.querySelector('[name="form_loaded_at"]')){const t=document.createElement('input');t.type='hidden';t.name='form_loaded_at';t.value=String(Date.now());form.appendChild(t)}}enrichForm();
async function notifyFallback(fd){try{const r=await fetch(form.action,{method:'POST',body:fd,headers:{Accept:'application/json'}});return r.ok}catch{return false}}
if(form){form.addEventListener('submit',async e=>{e.preventDefault();const btn=form.querySelector('button[type="submit"]');const status=form.querySelector('.form-status');const original=btn.textContent;btn.disabled=true;btn.textContent='Sending…';status.className='form-status';const fd=new FormData(form);const payload=Object.fromEntries(fd.entries());Object.assign(payload,{session_id:session,lead_source:attr.utm_source||'website',landing_page:location.pathname+location.search,referrer:attr.referrer,...attr});track('inquiry_submit',{form:'main_contact'});try{const res=await fetch(LEAD,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify(payload)});const data=await res.json().catch(()=>({}));if(!res.ok||!data.success)throw new Error(data.message||'storage_failed');status.textContent='Thank you — your inquiry was securely received. I’ll get back to you as soon as possible.';status.classList.add('show','p11-form-status-success');btn.textContent='Received';const notifyData=new FormData(form);notifyData.append('_subject',`Stored BWD lead ${data.lead_id||''}`);void notifyFallback(notifyData);form.reset();const timing=form.querySelector('[name="form_loaded_at"]');if(timing)timing.value=String(Date.now())}catch(err){const backedUp=await notifyFallback(fd);if(backedUp){status.textContent='Your message was sent through the backup delivery route. The internal lead system is temporarily unavailable, so I recommend keeping this page open until you receive a response.';status.classList.add('show','p11-form-status-error');btn.textContent='Sent by backup'}else{status.innerHTML='I could not safely store or deliver the inquiry. Please email <a href="mailto:BonebrakeWebsiteDesign@gmail.com"><strong>BonebrakeWebsiteDesign@gmail.com</strong></a> or call <a href="tel:+13312033717"><strong>331-203-3717</strong></a>.';status.classList.add('show','p11-form-status-error');btn.disabled=false;btn.textContent=original}}});}
})();