import { createClient } from 'npm:@supabase/supabase-js@2.95.0'

const OWNER='bonebrakewebsitedesign@gmail.com'
const now=()=>new Date().toISOString()
const clean=(v:unknown,max=1000)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)
const oldIso=(minutes:number)=>new Date(Date.now()-minutes*60_000).toISOString()
async function sha256(value:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function sameSecret(a:string,b:string){if(!a||!b)return false;const [x,y]=await Promise.all([sha256(a),sha256(b)]);return x===y}

Deno.serve(async(req:Request)=>{
  if(req.method!=='POST') return Response.json({ok:false,error:'method_not_allowed'},{status:405,headers:{'Cache-Control':'no-store'}})
  const url=Deno.env.get('SUPABASE_URL'),service=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}')['default']
  if(!url||!service) return Response.json({ok:false,error:'server_configuration_error'},{status:500})
  const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}})
  const {data:stored}=await db.from('integration_secrets').select('secret_value').eq('key','monitor_worker_secret').maybeSingle()
  const supplied=req.headers.get('x-bonebrake-monitor-key')||''
  let authorized=await sameSecret(supplied,String(stored?.secret_value||''))
  if(!authorized){const auth=req.headers.get('authorization')||'',jwt=auth.startsWith('Bearer ')?auth.slice(7):'';if(jwt){const {data:{user}}=await db.auth.getUser(jwt);authorized=String(user?.email||'').toLowerCase()===OWNER}}
  if(!authorized) return Response.json({ok:false,error:'monitor_auth_required'},{status:401,headers:{'Cache-Control':'no-store'}})
  let body:any={};try{body=await req.json()}catch{}
  const trigger=['cron','manual','certification'].includes(body?.trigger_source)?body.trigger_source:'cron'
  const {data:settings}=await db.from('automation_settings').select('*').eq('key','global').maybeSingle()
  if(!settings) return Response.json({ok:false,error:'settings_unavailable'},{status:503})
  if(!settings.monitoring_enabled && trigger==='cron') return Response.json({ok:true,status:'skipped',reason:'monitoring_disabled'},{headers:{'Cache-Control':'no-store'}})
  const {data:run,error:runError}=await db.from('automation_monitor_runs').insert({trigger_source:trigger,status:'running'}).select('id,started_at').single()
  if(runError||!run) return Response.json({ok:false,error:'monitor_run_create_failed'},{status:500})
  const seen=new Set<string>();let checks=0,recoveries=0,recovered=0,escalations=0
  const upsertIncident=async(spec:any)=>{
    const key=clean(spec.key,240);seen.add(key);const stamp=now()
    const {data:existing}=await db.from('automation_incidents').select('*').eq('incident_key',key).maybeSingle()
    if(existing){const nextStatus=['resolved','ignored'].includes(existing.status)?'open':existing.status;const {data}=await db.from('automation_incidents').update({updated_at:stamp,last_seen_at:stamp,status:nextStatus,resolved_at:null,resolved_reason:null,occurrence_count:Number(existing.occurrence_count||0)+1,category:spec.category,severity:spec.severity,title:clean(spec.title,500),detail:clean(spec.detail,4000),entity_type:spec.entity_type||null,entity_id:spec.entity_id||null,auto_recoverable:!!spec.auto_recoverable,recovery_strategy:spec.recovery_strategy||'none',max_auto_attempts:Number(spec.max_auto_attempts||0),last_payload:spec.payload||{}}).eq('id',existing.id).select('*').single();return data||existing}
    const {data}=await db.from('automation_incidents').insert({incident_key:key,category:spec.category,severity:spec.severity,title:clean(spec.title,500),detail:clean(spec.detail,4000),entity_type:spec.entity_type||null,entity_id:spec.entity_id||null,auto_recoverable:!!spec.auto_recoverable,recovery_strategy:spec.recovery_strategy||'none',max_auto_attempts:Number(spec.max_auto_attempts||0),last_payload:spec.payload||{}}).select('*').single();return data
  }
  const recovery=async(incident:any,strategy:string,work:()=>Promise<any>)=>{recoveries++;const {data:attempt}=await db.from('automation_recovery_attempts').insert({incident_id:incident.id,monitor_run_id:run.id,strategy,status:'executing'}).select('id').single();try{const result=await work();recovered++;await db.from('automation_recovery_attempts').update({status:'completed',completed_at:now(),result:result||{}}).eq('id',attempt?.id);await db.from('automation_incidents').update({status:'retrying',recovery_attempts:Number(incident.recovery_attempts||0)+1,next_retry_at:new Date(Date.now()+5*60_000).toISOString(),updated_at:now()}).eq('id',incident.id);return result}catch(error){const message=clean(error instanceof Error?error.message:String(error),800);await db.from('automation_recovery_attempts').update({status:'failed',completed_at:now(),error_message:message}).eq('id',attempt?.id);await db.from('automation_incidents').update({recovery_attempts:Number(incident.recovery_attempts||0)+1,updated_at:now()}).eq('id',incident.id);return null}}
  const escalate=async(incident:any,summary:string)=>{if(incident.escalation_action_id)return incident.escalation_action_id;const {data:existing}=await db.from('automation_actions').select('id').eq('action_type','investigate_monitoring_incident').eq('entity_type','monitoring_incident').eq('entity_id',incident.id).in('status',['pending','approved']).limit(1);let id=existing?.[0]?.id||null;if(!id){const {data:action}=await db.from('automation_actions').insert({action_type:'investigate_monitoring_incident',entity_type:'monitoring_incident',entity_id:incident.id,title:`Investigate: ${clean(incident.title,180)}`,summary:clean(summary,1000),risk_level:'approval',status:'pending',proposed_by:'monitoring',payload:{incident_id:incident.id,incident_key:incident.incident_key,category:incident.category,severity:incident.severity,recommended_effect:'owner_review_only'}}).select('id').single();id=action?.id||null;if(id)escalations++}if(id)await db.from('automation_incidents').update({status:'escalated',escalation_action_id:id,updated_at:now()}).eq('id',incident.id);return id}
  try{
    checks++
    const {data:stuckActions}=await db.from('automation_actions').select('id,action_type,title,status,updated_at,risk_level').eq('status','executing').lt('updated_at',oldIso(15)).limit(100)
    const unlockable=new Set(['run_prospect_audit','promote_prospect_to_crm','start_paid_project_fulfillment','prepare_paid_project_build','generate_paid_project_build','apply_paid_project_revision'])
    for(const a of stuckActions||[]){const can=unlockable.has(a.action_type);const inc=await upsertIncident({key:`automation:stuck:${a.id}`,category:'automation',severity:a.action_type==='deploy_paid_project_production'?'critical':'error',title:`Automation action stuck: ${a.title}`,detail:`${a.action_type} has remained executing for more than 15 minutes.`,entity_type:'automation_action',entity_id:a.id,auto_recoverable:can,recovery_strategy:can?'unlock':'escalate',max_auto_attempts:can?2:0,payload:{action_type:a.action_type,updated_at:a.updated_at}});if(can&&settings.auto_recovery_enabled&&Number(inc.recovery_attempts||0)<2){await recovery(inc,'unlock',async()=>{const {data,error}=await db.from('automation_actions').update({status:'approved',error_message:'Recovered from stale execution lock by monitoring worker.',updated_at:now(),execute_after:now()}).eq('id',a.id).eq('status','executing').select('id').maybeSingle();if(error||!data)throw new Error('stale_action_unlock_failed');return {action_id:a.id,status:'approved'}})}else if(!can||Number(inc.recovery_attempts||0)>=2)await escalate(inc,'The action cannot be safely retried automatically or has exhausted automatic recovery attempts.')}

    checks++
    const {data:failedActions}=await db.from('automation_actions').select('id,action_type,title,error_message,updated_at').eq('status','failed').gt('updated_at',oldIso(1440)).limit(100)
    for(const a of failedActions||[]){const critical=['deploy_paid_project_production'].includes(a.action_type);const inc=await upsertIncident({key:`automation:failed:${a.id}`,category:'automation',severity:critical?'critical':'error',title:`Automation failed: ${a.title}`,detail:a.error_message||`${a.action_type} failed.`,entity_type:'automation_action',entity_id:a.id,recovery_strategy:'escalate',payload:{action_type:a.action_type,error:a.error_message}});await escalate(inc,'A recent automation action failed and requires review before any further external effect.')}

    checks++
    const {data:stalePayments}=await db.from('stripe_payment_events').select('stripe_event_id,event_type,status,received_at,error_message').eq('status','processing').lt('received_at',oldIso(10)).limit(100)
    for(const p of stalePayments||[]){const inc=await upsertIncident({key:`payment:stale:${p.stripe_event_id}`,category:'payment',severity:'error',title:`Stripe event stuck processing: ${p.event_type}`,detail:'The event has held a processing claim for more than 10 minutes.',entity_type:'stripe_event',auto_recoverable:true,recovery_strategy:'reset_retryable',max_auto_attempts:2,payload:{stripe_event_id:p.stripe_event_id,event_type:p.event_type}});if(settings.auto_recovery_enabled&&Number(inc.recovery_attempts||0)<2){await recovery(inc,'reset_retryable',async()=>{const {data,error}=await db.from('stripe_payment_events').update({status:'received',error_message:'Recovered stale processing claim; awaiting Stripe retry/reconciliation.'}).eq('stripe_event_id',p.stripe_event_id).eq('status','processing').select('stripe_event_id').maybeSingle();if(error||!data)throw new Error('stripe_claim_reset_failed');return {stripe_event_id:p.stripe_event_id,status:'received'}})}else if(Number(inc.recovery_attempts||0)>=2)await escalate(inc,'Stripe processing remained stuck after automatic claim resets. Reconcile the payment event before taking customer-facing action.')}
    const {data:failedPayments}=await db.from('stripe_payment_events').select('stripe_event_id,event_type,error_message,received_at').eq('status','failed').gt('received_at',oldIso(4320)).limit(100)
    for(const p of failedPayments||[]){const inc=await upsertIncident({key:`payment:failed:${p.stripe_event_id}`,category:'payment',severity:'critical',title:`Stripe event failed: ${p.event_type}`,detail:p.error_message||'A live payment event failed processing.',entity_type:'stripe_event',recovery_strategy:'escalate',payload:{stripe_event_id:p.stripe_event_id,event_type:p.event_type}});await escalate(inc,'Payment state is high-risk and will not be guessed or replayed automatically. Reconciliation is required.')}

    checks++
    const {data:expiredIntakes}=await db.from('client_intake_requests').select('id,project_id,client_email,expires_at').eq('status','pending').lt('expires_at',now()).limit(100)
    for(const i of expiredIntakes||[]){const inc=await upsertIncident({key:`fulfillment:intake_expired:${i.id}`,category:'fulfillment',severity:'warning',title:'Client intake link expired',detail:`The paid-client intake request expired before submission${i.client_email?` for ${i.client_email}`:''}.`,entity_type:'project',entity_id:i.project_id,recovery_strategy:'escalate',payload:{intake_request_id:i.id,expires_at:i.expires_at}});await escalate(inc,'A fresh intake credential should be issued only through the controlled fulfillment flow.')}
    const {data:stuckJobs}=await db.from('project_fulfillment_jobs').select('id,project_id,status,updated_at,failure_code,failure_message').in('status',['generating','qa']).lt('updated_at',oldIso(30)).limit(100)
    for(const j of stuckJobs||[]){const inc=await upsertIncident({key:`fulfillment:stuck_job:${j.id}`,category:'fulfillment',severity:'error',title:`Fulfillment job stuck in ${j.status}`,detail:'The job has made no progress for more than 30 minutes.',entity_type:'project',entity_id:j.project_id,recovery_strategy:'escalate',payload:{job_id:j.id,status:j.status}});await escalate(inc,'AI generation/QA did not complete. Preserve the current artifact state and review before retrying.')}
    const {data:stuckRevisions}=await db.from('project_revision_requests').select('id,project_id,status,updated_at').eq('status','processing').lt('updated_at',oldIso(30)).limit(100)
    for(const r of stuckRevisions||[]){const inc=await upsertIncident({key:`fulfillment:stuck_revision:${r.id}`,category:'fulfillment',severity:'error',title:'Client revision processing is stuck',detail:'A revision request has remained processing for more than 30 minutes.',entity_type:'project',entity_id:r.project_id,auto_recoverable:true,recovery_strategy:'unlock',max_auto_attempts:1,payload:{revision_id:r.id}});if(settings.auto_recovery_enabled&&Number(inc.recovery_attempts||0)<1){await recovery(inc,'unlock',async()=>{const {data,error}=await db.from('project_revision_requests').update({status:'approved',error_message:'Recovered stale processing lock; revision is retryable.',updated_at:now()}).eq('id',r.id).eq('status','processing').select('id').maybeSingle();if(error||!data)throw new Error('revision_unlock_failed');return {revision_id:r.id,status:'approved'}})}else await escalate(inc,'Revision processing could not be safely completed and requires a controlled retry.')}

    checks++
    const {data:badDomains}=await db.from('project_site_domains').select('id,project_id,hostname,status,ssl_status,failure_code,failure_message').or('status.eq.error,ssl_status.eq.error').limit(100)
    for(const d of badDomains||[]){const inc=await upsertIncident({key:`domain:failure:${d.id}`,category:'domain',severity:'error',title:`Domain/SSL issue: ${d.hostname}`,detail:d.failure_message||`Domain status ${d.status}; SSL status ${d.ssl_status}.`,entity_type:'project',entity_id:d.project_id,recovery_strategy:'escalate',payload:{domain_id:d.id,hostname:d.hostname,status:d.status,ssl_status:d.ssl_status,failure_code:d.failure_code}});await escalate(inc,'Domain or SSL state requires verification before production deployment can proceed.')}

    checks++
    const {data:activeReleases}=await db.from('project_release_candidates').select('id,project_id,artifact_id,previous_release_id,deployment_url,deployment_health').eq('status','deployed').eq('is_active',true).limit(100)
    for(const rel of activeReleases||[]){const [{data:domain},{data:artifact}]=await Promise.all([db.from('project_site_domains').select('id,hostname,status,ssl_status').eq('project_id',rel.project_id).eq('is_primary',true).maybeSingle(),db.from('project_generated_artifacts').select('content_sha256').eq('id',rel.artifact_id).maybeSingle()]);if(!domain||domain.status!=='active'||domain.ssl_status!=='ready'||!artifact?.content_sha256){const inc=await upsertIncident({key:`production:configuration:${rel.id}`,category:'production',severity:'critical',title:'Active release has invalid production configuration',detail:'An active release is missing an active SSL-ready primary domain or artifact hash.',entity_type:'project',entity_id:rel.project_id,recovery_strategy:'escalate',payload:{release_id:rel.id,domain:domain||null}});await escalate(inc,'Production configuration is inconsistent. Do not publish another release until reconciled.');continue}
      let healthy=false,actualHash='',httpStatus=0,errorText='';try{const res=await fetch(`${url}/functions/v1/client-site-resolve?host=${encodeURIComponent(domain.hostname)}`,{signal:AbortSignal.timeout(12000)});httpStatus=res.status;if(res.ok){const text=await res.text();actualHash=await sha256(text);healthy=actualHash===artifact.content_sha256}else errorText=`HTTP ${res.status}`}catch(error){errorText=clean(error instanceof Error?error.message:String(error),500)}
      await db.from('project_site_domains').update({last_checked_at:now(),failure_code:healthy?null:'monitor_health_failed',failure_message:healthy?null:(errorText||'content hash mismatch'),updated_at:now()}).eq('id',domain.id)
      if(healthy){await db.from('project_release_candidates').update({deployment_health:{...(rel.deployment_health||{}),status:'healthy',monitor_smoke_passed:true,content_sha256:actualHash,checked_at:now()},updated_at:now()}).eq('id',rel.id);continue}
      const inc=await upsertIncident({key:`production:unhealthy:${rel.id}`,category:'production',severity:'critical',title:`Production site unhealthy: ${domain.hostname}`,detail:errorText||`Content hash mismatch (HTTP ${httpStatus}).`,entity_type:'project',entity_id:rel.project_id,auto_recoverable:!!rel.previous_release_id,recovery_strategy:rel.previous_release_id?'rollback':'escalate',max_auto_attempts:rel.previous_release_id?1:0,payload:{release_id:rel.id,hostname:domain.hostname,http_status:httpStatus,actual_hash:actualHash,expected_hash:artifact.content_sha256,previous_release_id:rel.previous_release_id}})
      if(rel.previous_release_id&&settings.auto_recovery_enabled&&Number(inc.recovery_attempts||0)<1){const result=await recovery(inc,'rollback',async()=>{const {data,error}=await db.rpc('phase14_revert_project_activation',{p_release_id:rel.id,p_reason:'monitoring_unhealthy_release'});if(error||!data)throw new Error(error?.message||'automatic_rollback_failed');return data});if(result){await db.from('automation_incidents').update({status:'resolved',resolved_at:now(),resolved_reason:'Automatically rolled back to previous healthy production release.',updated_at:now()}).eq('id',inc.id);await db.from('activity').insert({entity_type:'project',entity_id:rel.project_id,action:'monitoring_automatic_production_rollback',detail:{release_id:rel.id,rollback:result}})}}else await escalate(inc,'Production health check failed and no safe automatic rollback was available.')
    }

    checks++
    const {data:open}=await db.from('automation_incidents').select('id,incident_key,status,last_seen_at').in('status',['open','retrying']).lt('last_seen_at',run.started_at).limit(500)
    for(const inc of open||[])if(!seen.has(inc.incident_key))await db.from('automation_incidents').update({status:'resolved',resolved_at:now(),resolved_reason:'Condition was not observed on the next monitoring pass.',updated_at:now(),next_retry_at:null}).eq('id',inc.id)

    const {data:openCounts}=await db.from('automation_incidents').select('severity,status').in('status',['open','retrying','escalated'])
    const counts={critical:0,error:0,warning:0,info:0};for(const i of openCounts||[])(counts as any)[i.severity]=Number((counts as any)[i.severity]||0)+1
    const summary={open_incidents:counts,seen_this_run:seen.size,capabilities:{monitoring_enabled:!!settings.monitoring_enabled,auto_recovery_enabled:!!settings.auto_recovery_enabled},safe_recovery_policy:'locks/payment-claims/known-good-production-rollback only'}
    await db.from('automation_monitor_runs').update({status:'completed',completed_at:now(),checks_run:checks,incidents_seen:seen.size,recoveries_attempted:recoveries,recoveries_succeeded:recovered,escalations_created:escalations,summary}).eq('id',run.id)
    return Response.json({ok:true,run_id:run.id,...summary,recoveries_attempted:recoveries,recoveries_succeeded:recovered,escalations_created:escalations},{headers:{'Cache-Control':'no-store'}})
  }catch(error){const message=clean(error instanceof Error?error.message:String(error),1000);await db.from('automation_monitor_runs').update({status:'failed',completed_at:now(),checks_run:checks,incidents_seen:seen.size,recoveries_attempted:recoveries,recoveries_succeeded:recovered,escalations_created:escalations,error_message:message}).eq('id',run.id);return Response.json({ok:false,error:'monitor_run_failed',detail:message,run_id:run.id},{status:500,headers:{'Cache-Control':'no-store'}})}
})