import fs from 'node:fs/promises';
import path from 'node:path';
const root=process.cwd();
const required=['index.html','work.html','website-audit.html','audit-report.html','dashboard.html','proposal.html','phase11.css','phase12.css','phase13.css','site.js','phase12.js','phase13-dashboard.js','audit-page.js','audit-report.js','proposal.js','dashboard.js','case-aurelia.html','case-northstar.html','case-oak-stone.html','case-westside-auto-lab.html','case-lakeview-dental.html','aurelia.html','northstar.html','oak-stone.html','westside-auto-lab.html','lakeview-dental.html','privacy.html','terms.html','robots.txt','sitemap.xml','vercel.json','api/health.js','api/audit.js','api/lead.js','.github/workflows/phase14-ci.yml','.well-known/security.txt','OPERATIONS.md','tests/phase14.test.mjs'];
const failures=[];for(const file of required){try{await fs.access(path.join(root,file))}catch{failures.push(`Missing required production file: ${file}`)}}
for(const forbidden of ['api/phase12-owner-bootstrap.js','api/phase13-owner-bootstrap.js','api/phase14-owner-login-qa.js','.github/workflows/phase12-ci.yml','.github/workflows/phase13-ci.yml']){try{await fs.access(path.join(root,forbidden));failures.push(`Temporary or stale release artifact must not ship: ${forbidden}`)}catch{}}
try{const entries=await fs.readdir(path.join(root,'api'),{withFileTypes:true});for(const entry of entries.filter(x=>x.isFile()&&x.name.endsWith('.js'))){const source=await fs.readFile(path.join(root,'api',entry.name),'utf8');if(source.includes('/functions/v1/phase12-owner-bootstrap'))failures.push(`Stale Phase 12 bootstrap bridge reference in api/${entry.name}`);if(/[?&]token=[A-Za-z0-9_-]{24,}/.test(source))failures.push(`Hard-coded long-lived query token in api/${entry.name}`)}}catch(error){failures.push(`Unable to inspect API bridge sources: ${error.message}`)}
let vercel={};try{vercel=JSON.parse(await fs.readFile(path.join(root,'vercel.json'),'utf8'))}catch(error){failures.push(`vercel.json is not valid JSON: ${error.message}`)}
const globalHeaders=vercel?.headers?.find?.(entry=>entry.source==='/(.*)')?.headers||[],headerNames=new Set(globalHeaders.map(item=>String(item.key||'').toLowerCase()));for(const header of ['x-content-type-options','x-frame-options','referrer-policy','permissions-policy','strict-transport-security'])if(!headerNames.has(header))failures.push(`Missing security header: ${header}`);
try{const pkg=JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8'));if(pkg.version!=='14.0.0')failures.push(`package.json release must be 14.0.0, found ${pkg.version||'missing'}`)}catch(error){failures.push(`package.json invalid: ${error.message}`)}
try{const operations=await fs.readFile(path.join(root,'OPERATIONS.md'),'utf8');if(!operations.includes('Phase 14 Operations')||!operations.includes('Release: `14.0.0`')||!operations.includes('Build: `phase14-six-figure-certification`'))failures.push('OPERATIONS.md does not describe the Phase 14 release');if(!operations.includes('Owner authentication')||!operations.includes('Production domain')||!operations.includes('Certification boundaries'))failures.push('OPERATIONS.md omits certification boundaries')}catch{}
try{const index=await fs.readFile(path.join(root,'index.html'),'utf8');for(const text of ['Bonebrake Web Design','331-203-3717','BonebrakeWebsiteDesign@gmail.com'])if(!index.includes(text))failures.push(`index.html missing business identity: ${text}`);if(!/<meta\s+name=["']viewport["']/i.test(index))failures.push('index.html missing viewport metadata')}catch{}
try{const site=await fs.readFile(path.join(root,'site.js'),'utf8');if(!site.includes('/functions/v1/lead-intake'))failures.push('persistent lead intake missing');if(!site.includes('notifyFallback'))failures.push('emergency lead fallback missing');if(!site.includes('/functions/v1/analytics-track'))failures.push('first-party analytics missing');if(!site.includes('phase12.js'))failures.push('Phase 12 public art direction missing')}catch{}
try{const p12=await fs.readFile(path.join(root,'phase12.js'),'utf8');if(!p12.includes('p12-diagnostic'))failures.push('signature diagnostic missing');for(const f of ['case-aurelia.html','case-northstar.html','case-oak-stone.html','case-westside-auto-lab.html','case-lakeview-dental.html'])if(!p12.includes(f))failures.push(`Homepage case routing missing ${f}`)}catch{}
const budgets={'northstar.html':100_000,'phase13.css':20_000,'phase13-dashboard.js':35_000,'proposal.html':20_000,'proposal.js':20_000};for(const [file,max] of Object.entries(budgets)){try{const stat=await fs.stat(path.join(root,file));if(stat.size>=max)failures.push(`${file} exceeds ${max} byte budget (${stat.size})`)}catch{}}
try{const health=await fs.readFile(path.join(root,'api/health.js'),'utf8');if(!health.includes("const RELEASE = '14.0.0'"))failures.push('health release is not 14.0.0');if(!health.includes("const BUILD = 'phase14-six-figure-certification'"))failures.push('health build identity is stale');if(!health.includes('/functions/v1/system-health'))failures.push('health does not verify persistent data plane');if(!health.includes('proposal_workflow'))failures.push('health does not expose proposal capability');if(!health.includes('launch_readiness'))failures.push('health does not expose launch readiness');if(!health.includes('VERCEL_GIT_COMMIT_SHA'))failures.push('health does not expose Git commit traceability');if(!health.includes('owner_identity_bootstrapped'))failures.push('health omits owner bootstrap certification state');if(/phase11_preview|phase11_production|phase12_preview|phase12_production|phase13_preview|phase13_production/.test(health))failures.push('health contains stale release state')}catch{}
try{const workflow=await fs.readFile(path.join(root,'.github/workflows/phase14-ci.yml'),'utf8');if(!/Phase 14 Certification Gate/.test(workflow))failures.push('CI does not identify Phase 14 certification');if(!/phase14-\*/.test(workflow))failures.push('CI does not run on Phase 14 branches')}catch{}
try{const dashboard=await fs.readFile(path.join(root,'dashboard.js'),'utf8'),p13=await fs.readFile(path.join(root,'phase13-dashboard.js'),'utf8'),html=await fs.readFile(path.join(root,'dashboard.html'),'utf8');if(!dashboard.toLowerCase().includes('bonebrakewebsitedesign@gmail.com'))failures.push('owner authorization target missing');if(!dashboard.includes('shouldCreateUser:false')||dashboard.includes('shouldCreateUser:true'))failures.push('dashboard arbitrary signup protection invalid');for(const table of ["'proposals'","'project_checklist'","'projects'","'leads'"])if(!p13.includes(table))failures.push(`Operating dashboard missing ${table}`);if(!p13.includes('paid_amount'))failures.push('recorded paid value missing');if(!html.includes('phase13-dashboard.js')||!html.includes('phase13.css'))failures.push('dashboard does not load sales/delivery operating layer')}catch{}
try{const proposal=await fs.readFile(path.join(root,'proposal.js'),'utf8'),html=await fs.readFile(path.join(root,'proposal.html'),'utf8');if(!proposal.includes('/functions/v1/proposal-view'))failures.push('proposal view endpoint missing');if(!/noindex,nofollow,noarchive/i.test(html))failures.push('tokenized proposal must be noindex');for(const marker of ['lead_id','session_id','requested_by','owner_id'])if(proposal.includes(marker))failures.push(`public proposal client references private field ${marker}`)}catch{}
try{const audit=await fs.readFile(path.join(root,'audit-page.js'),'utf8'),viewer=await fs.readFile(path.join(root,'audit-report.js'),'utf8');if(!audit.includes('share_token'))failures.push('audit share token missing');if(!viewer.includes('/functions/v1/audit-report'))failures.push('audit report endpoint missing');for(const marker of ['requested_by','session_id','lead_id'])if(viewer.includes(marker))failures.push(`audit client references private field ${marker}`)}catch{}
try{const files=['site.js','phase12.js','phase13-dashboard.js','audit-page.js','audit-report.js','proposal.js','dashboard.js','website-audit.html','audit-report.html','proposal.html','dashboard.html'];for(const file of files){const source=await fs.readFile(path.join(root,file),'utf8');if(source.includes('sb_secret_')||source.includes('SUPABASE_SERVICE_ROLE_KEY')||source.includes('service_role'))failures.push(`${file} contains privileged credential marker`)}}catch{}
try{const sitemap=await fs.readFile(path.join(root,'sitemap.xml'),'utf8'),robots=await fs.readFile(path.join(root,'robots.txt'),'utf8');for(const p of ['work.html','website-audit.html','case-aurelia.html','case-northstar.html','case-oak-stone.html','case-westside-auto-lab.html','case-lakeview-dental.html'])if(!sitemap.includes(p))failures.push(`sitemap missing ${p}`);for(const p of ['dashboard.html','audit-report.html','proposal.html']){if(sitemap.includes(p))failures.push(`${p} must stay out of sitemap`);if(!new RegExp(`Disallow:\s*\/${p.replace('.','\.')}`,'i').test(robots))failures.push(`robots.txt must disallow ${p}`)}}catch{}
try{const security=await fs.readFile(path.join(root,'.well-known/security.txt'),'utf8');if(!/^Contact:\s*mailto:/mi.test(security))failures.push('security.txt missing mailto');if(!/^Expires:/mi.test(security))failures.push('security.txt missing expiry')}catch{}
if(failures.length){console.error(`Phase 14 certification static checks failed (${failures.length}):`);for(const failure of failures)console.error(`- ${failure}`);process.exit(1)}console.log(`Phase 14 certification static checks passed (${required.length} required files + release, UX, sales, delivery, privacy, performance, data-plane, and security checks).`);
