import { createClient } from 'npm:@supabase/supabase-js@2.95.0'

const OWNER='bonebrakewebsitedesign@gmail.com'
const clean=(v:unknown,max=1000)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)
const uuidRe=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const now=()=>new Date().toISOString()
function randomToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function sha256(value:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function validateHtml(html:string){const problems:string[]=[];if(typeof html!=='string'||html.length<3000||html.length>180000)problems.push('html_size_invalid');if(!/^\s*<!doctype html>/i.test(html))problems.push('doctype_missing');for(const marker of ['<html','<head','<body','name="viewport"'])if(!html.toLowerCase().includes(marker.toLowerCase()))problems.push(`missing_${marker.replace(/[^a-z]/gi,'')}`);const forbidden:any[]=[[/<(?:iframe|object|embed|base|form)\b/i,'forbidden_element'],[/<script[^>]+\bsrc\s*=/i,'external_script'],[/<link\b/i,'external_link_element'],[/<meta[^>]+http-equiv\s*=/i,'meta_http_equiv'],[/https?:\/\//i,'external_url'],[/(?:fetch|XMLHttpRequest|WebSocket|EventSource)\s*\(/i,'network_api'],[/navigator\.sendBeacon/i,'network_api'],[/javascript\s*:/i,'javascript_url'],[/document\.cookie/i,'cookie_access'],[/(?:localStorage|sessionStorage)/i,'browser_storage'],[/(?:\beval|\bFunction)\s*\(/i,'dynamic_code']];for(const [pattern,label] of forbidden)if(pattern.test(html))problems.push(label);return [...new Set(problems)]}
function approvedWorkerUrl(value:unknown){const raw=clean(value,500)||'https://bwdnorth.com/api/ai-site-builder';try{const u=new URL(raw);const allowedHost=u.hostname==='bwdnorth.com'||u.hostname==='www.bwdnorth.com'||u.hostname.endsWith('.vercel.app');if(u.protocol!=='https:'||!allowedHost||u.pathname!=='/api/ai-site-builder')return null;u.search='';u.hash='';return u.toString().replace(/\/$/,'')}catch{return null}}

Deno.serve(async(req:Request)=>{
  if(req.method!=='POST') return Response.json({ok:false,error:'method_not_allowed'},{status:405})
  const auth=req.headers.get('authorization')||'',jwt=auth.startsWith('Bearer ')?auth.slice(7):''
  if(!jwt) return Response.json({ok:false,error:'authentication_required'},{status:401})
  const url=Deno.env.get('SUPABASE_URL'),secret=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}')['default']
  if(!url||!secret) return Response.json({ok:false,error:'server_configuration_error'},{status:500})
  const db=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}})
  const {data:{user},error:userError}=await db.auth.getUser(jwt)
  if(userError||!user||String(user.email||'').toLowerCase()!==OWNER) return Response.json({ok:false,error:'owner_only'},{status:403})
  let body:any;try{body=await req.json()}catch{return Response.json({ok:false,error:'invalid_json'},{status:400})}
  const actionId=clean(body?.action_id,80);if(!uuidRe.test(actionId)) return Response.json({ok:false,error:'valid_action_id_required'},{status:400})
  const [{data:settings},{data:action}]=await Promise.all([db.from('automation_settings').select('*').eq('key','global').maybeSingle(),db.from('automation_actions').select('*').eq('id',actionId).maybeSingle()])
  if(!settings||!action) return Response.json({ok:false,error:'action_or_settings_unavailable'},{status:404})
  if(action.status==='completed') return Response.json({ok:true,already_completed:true,result:action.result||null})
  if(action.action_type!=='apply_paid_project_revision'||action.status!=='approved') return Response.json({ok:false,error:'revision_action_not_approved'},{status:409})
  if(!settings.autopilot_enabled||!settings.fulfillment_enabled) return Response.json({ok:false,error:'fulfillment_disabled'},{status:423})
  const workerUrl=approvedWorkerUrl(settings.config?.ai_builder_url);if(!workerUrl) return Response.json({ok:false,error:'ai_builder_url_invalid'},{status:500})
  const projectId=String(action.entity_id||action.payload?.project_id||''),jobId=String(action.payload?.fulfillment_job_id||''),artifactId=String(action.payload?.artifact_id||''),revisionId=String(action.payload?.revision_id||'')
  if(![projectId,jobId,artifactId,revisionId].every(x=>uuidRe.test(x))) return Response.json({ok:false,error:'revision_targets_invalid'},{status:400})
  const [{data:project},{data:job},{data:baseArtifact},{data:revision}]=await Promise.all([
    db.from('projects').select('*').eq('id',projectId).maybeSingle(),db.from('project_fulfillment_jobs').select('*').eq('id',jobId).eq('project_id',projectId).maybeSingle(),db.from('project_generated_artifacts').select('*').eq('id',artifactId).eq('project_id',projectId).maybeSingle(),db.from('project_revision_requests').select('*').eq('id',revisionId).eq('project_id',projectId).maybeSingle()
  ])
  if(!project||project.payment_state!=='paid'||Number(project.paid_amount)<Number(project.agreed_price)) return Response.json({ok:false,error:'paid_project_required'},{status:409})
  if(!job||!['ready_for_review','approved'].includes(job.status)) return Response.json({ok:false,error:'job_not_revision_ready'},{status:409})
  if(!baseArtifact||!['review','approved'].includes(baseArtifact.status)) return Response.json({ok:false,error:'base_artifact_unavailable'},{status:409})
  if(!revision||!['pending','approved'].includes(revision.status)||revision.artifact_id!==baseArtifact.id) return Response.json({ok:false,error:'revision_not_ready'},{status:409})
  const {data:claimed,error:claimError}=await db.from('automation_actions').update({status:'executing',updated_at:now(),error_message:null}).eq('id',action.id).eq('status','approved').select('id').maybeSingle();if(claimError||!claimed)return Response.json({ok:false,error:'action_already_claimed'},{status:409})
  const fail=async(message:string,code='revision_failed')=>{const m=clean(message,500);await db.from('project_fulfillment_jobs').update({status:'ready_for_review',failure_code:code,failure_message:m,updated_at:now()}).eq('id',job.id).eq('status','generating');await db.from('project_revision_requests').update({status:'failed',error_message:m,processed_at:now(),updated_at:now()}).eq('id',revision.id).eq('status','processing');await db.from('generation_worker_tokens').update({status:'cancelled'}).eq('action_id',action.id).eq('status','issued');await db.from('automation_actions').update({status:'failed',error_message:m,result:{error:m},updated_at:now()}).eq('id',action.id).eq('status','executing');return Response.json({ok:false,error:m},{status:500,headers:{'Cache-Control':'no-store'}})}
  await db.from('project_revision_requests').update({status:'processing',updated_at:now()}).eq('id',revision.id).in('status',['pending','approved'])
  const {data:jobClaim}=await db.from('project_fulfillment_jobs').update({status:'generating',failure_code:null,failure_message:null,updated_at:now()}).eq('id',job.id).in('status',['ready_for_review','approved']).select('id').maybeSingle();if(!jobClaim)return await fail('fulfillment_job_revision_claim_failed','job_claim_failed')
  const workerToken=randomToken(),workerHash=await sha256(workerToken),workerExpires=new Date(Date.now()+5*60*1000).toISOString()
  const {error:tokenError}=await db.from('generation_worker_tokens').insert({action_id:action.id,project_id:project.id,fulfillment_job_id:job.id,token_hash:workerHash,status:'issued',expires_at:workerExpires,metadata:{worker_url:workerUrl,preview_only:true,mode:'revision',revision_id:revision.id,base_artifact_id:baseArtifact.id}});if(tokenError)return await fail('worker_token_issue_failed','worker_authorization_failed')
  let worker:any;try{const response=await fetch(workerUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({worker_token:workerToken,action_id:action.id,fulfillment_job_id:job.id}),signal:AbortSignal.timeout(112000)});worker=await response.json().catch(()=>({}));if(!response.ok||worker?.ok!==true)return await fail(worker?.error||`ai_worker_${response.status}`,'ai_worker_failed')}catch(error){return await fail(error instanceof Error?error.message:'ai_worker_unreachable','ai_worker_failed')}
  const artifact=worker?.artifact||{},html=String(artifact.html||''),problems=validateHtml(html);if(problems.length)return await fail(`revised_site_safety_validation_failed:${problems.join(',')}`,'artifact_safety_failed');if(artifact.quality_checks?.passed!==true)return await fail('revised_site_quality_validation_missing','artifact_quality_failed')
  const contentHash=await sha256(html),previewToken=randomToken(),previewHash=await sha256(previewToken),previewExpires=new Date(Date.now()+30*24*60*60*1000).toISOString();const {data:versions}=await db.from('project_generated_artifacts').select('version').eq('fulfillment_job_id',job.id).order('version',{ascending:false}).limit(1);const version=Math.max(0,Number(versions?.[0]?.version||0))+1;const qaNotes=Array.isArray(artifact.qa_notes)?artifact.qa_notes.map((x:any)=>clean(x,500)).filter(Boolean).slice(0,12):[]
  const {data:saved,error:saveError}=await db.from('project_generated_artifacts').insert({project_id:project.id,fulfillment_job_id:job.id,source_action_id:action.id,version,status:'review',title:clean(artifact.title,240),summary:clean(artifact.summary,1200),html,content_sha256:contentHash,qa_notes:qaNotes,preview_token_hash:previewHash,preview_expires_at:previewExpires}).select('id').single();if(saveError||!saved)return await fail('revised_artifact_persistence_failed','artifact_persistence_failed')
  const previewUrl=`${url}/functions/v1/project-preview?t=${encodeURIComponent(previewToken)}`,finishedAt=now();const qaReport={passed:true,preview_only:true,production_release_authorized:false,content_sha256:contentHash,safety_checks:['self_contained','no_external_urls','no_external_scripts','no_network_apis','no_forms','no_browser_storage'],quality_checks:artifact.quality_checks||{},model:clean(artifact.model,100),notes:qaNotes,revision_id:revision.id,base_artifact_id:baseArtifact.id}
  await db.from('project_generated_artifacts').update({status:'archived',updated_at:finishedAt}).eq('id',baseArtifact.id).in('status',['review','approved'])
  await db.from('project_revision_requests').update({status:'applied',applied_artifact_id:saved.id,processed_at:finishedAt,error_message:null,updated_at:finishedAt}).eq('id',revision.id).eq('status','processing')
  await db.from('project_fulfillment_jobs').update({status:'ready_for_review',preview_url:previewUrl,generated_at:finishedAt,qa_completed_at:finishedAt,qa_report:qaReport,updated_at:finishedAt}).eq('id',job.id).eq('status','generating')
  await db.from('projects').update({revision_status:'in_progress',current_milestone:'preview_ready',next_action:'review_generated_preview',updated_at:finishedAt}).eq('id',project.id)
  const {data:existing}=await db.from('automation_actions').select('id').eq('action_type','review_paid_project_preview').eq('entity_type','project').eq('entity_id',project.id).in('status',['pending','approved','executing']).limit(1);let reviewActionId=existing?.[0]?.id||null;if(!reviewActionId){const {data:review}=await db.from('automation_actions').insert({action_type:'review_paid_project_preview',entity_type:'project',entity_id:project.id,title:`Review revised website for ${project.client_name}`,summary:`Client revision applied to preview version ${version}. Automated QA passed; review the new private preview.`,risk_level:'approval',status:'pending',proposed_by:'revision_worker',payload:{project_id:project.id,fulfillment_job_id:job.id,artifact_id:saved.id,preview_url:previewUrl,content_sha256:contentHash,external_effect:'owner_preview_review_only',production_release_authorized:false}}).select('id').single();reviewActionId=review?.id||null}
  await db.from('activity').insert({entity_type:'project',entity_id:project.id,action:'client_revision_applied',detail:{revision_id:revision.id,base_artifact_id:baseArtifact.id,artifact_id:saved.id,version,review_action_id:reviewActionId}})
  const result={project_id:project.id,fulfillment_job_id:job.id,revision_id:revision.id,artifact_id:saved.id,version,review_action_id:reviewActionId,preview_url:previewUrl,production_release_authorized:false};await db.from('automation_actions').update({status:'completed',result,executed_at:finishedAt,updated_at:finishedAt}).eq('id',action.id).eq('status','executing');return Response.json({ok:true,status:'completed',result},{headers:{'Cache-Control':'no-store'}})
})
