alter table public.project_site_domains
  add column if not exists domain_zone text,
  add column if not exists domain_kind text,
  add column if not exists dns_status text not null default 'pending',
  add column if not exists host_status text not null default 'not_requested',
  add column if not exists dns_record_type text,
  add column if not exists dns_record_name text,
  add column if not exists dns_record_value text,
  add column if not exists dns_observed jsonb not null default '{}'::jsonb,
  add column if not exists dns_checked_at timestamptz,
  add column if not exists dns_ready_at timestamptz,
  add column if not exists host_verified_at timestamptz,
  add column if not exists setup_token_hash text,
  add column if not exists setup_token_expires_at timestamptz,
  add column if not exists onboarding_completed_at timestamptz,
  add column if not exists check_count integer not null default 0,
  add column if not exists last_https_status integer;

do $$ begin
  if not exists(select 1 from pg_constraint where conname='project_site_domains_domain_kind_check') then
    alter table public.project_site_domains add constraint project_site_domains_domain_kind_check check (domain_kind is null or domain_kind in ('apex','subdomain'));
  end if;
  if not exists(select 1 from pg_constraint where conname='project_site_domains_dns_status_check') then
    alter table public.project_site_domains add constraint project_site_domains_dns_status_check check (dns_status in ('pending','ready','error'));
  end if;
  if not exists(select 1 from pg_constraint where conname='project_site_domains_host_status_check') then
    alter table public.project_site_domains add constraint project_site_domains_host_status_check check (host_status in ('not_requested','approval_pending','attached','verification_required','error'));
  end if;
  if not exists(select 1 from pg_constraint where conname='project_site_domains_check_count_check') then
    alter table public.project_site_domains add constraint project_site_domains_check_count_check check (check_count >= 0);
  end if;
end $$;

create unique index if not exists project_site_domains_setup_token_hash_idx on public.project_site_domains(setup_token_hash) where setup_token_hash is not null;
create index if not exists project_site_domains_onboarding_idx on public.project_site_domains(host_status,dns_status,ssl_status,last_checked_at) where status not in ('active','disabled');

create table if not exists public.domain_onboarding_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  domain_id uuid not null references public.project_site_domains(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  event_type text not null,
  source text not null default 'system' check (source in ('owner','client','scheduler','system','vercel')),
  detail jsonb not null default '{}'::jsonb
);
create index if not exists domain_onboarding_events_domain_idx on public.domain_onboarding_events(domain_id,created_at desc);
create index if not exists domain_onboarding_events_project_idx on public.domain_onboarding_events(project_id,created_at desc);
alter table public.domain_onboarding_events enable row level security;
revoke all on public.domain_onboarding_events from anon;
revoke all on public.domain_onboarding_events from authenticated;
grant select,insert,update,delete on public.domain_onboarding_events to authenticated;
drop policy if exists owner_all_domain_onboarding_events on public.domain_onboarding_events;
create policy owner_all_domain_onboarding_events on public.domain_onboarding_events for all to authenticated
  using (lower(coalesce((select auth.jwt())->>'email',''))='bonebrakewebsitedesign@gmail.com')
  with check (lower(coalesce((select auth.jwt())->>'email',''))='bonebrakewebsitedesign@gmail.com');

alter table public.automation_settings
  add column if not exists domain_onboarding_enabled boolean not null default false,
  add column if not exists domain_check_interval_minutes integer not null default 15,
  add column if not exists vercel_host_project_id text,
  add column if not exists vercel_host_project_name text,
  add column if not exists vercel_team_id text;

do $$ begin
  if not exists(select 1 from pg_constraint where conname='automation_settings_domain_check_interval_check') then
    alter table public.automation_settings add constraint automation_settings_domain_check_interval_check check (domain_check_interval_minutes between 5 and 1440);
  end if;
end $$;

update public.automation_settings set
  domain_onboarding_enabled=true,
  domain_check_interval_minutes=15,
  vercel_host_project_id='prj_aamMF6oLvfO6DnkLPEAcdBjnNRXo',
  vercel_host_project_name='bonebrake-complete-site-1',
  vercel_team_id='team_nwkEzCFo7TVWsqPidGNM0MwA',
  updated_at=now()
where key='global';

do $$
declare s text; existing text;
begin
  select secret_value into existing from public.integration_secrets where key='domain_onboarding_worker_secret';
  if existing is null then
    s:=encode(gen_random_bytes(32),'hex');
    insert into public.integration_secrets(key,secret_value) values('domain_onboarding_worker_secret',s)
      on conflict(key) do update set secret_value=excluded.secret_value,updated_at=now();
  else s:=existing; end if;
  if not exists(select 1 from vault.decrypted_secrets where name='bonebrake_domain_onboarding_worker_secret') then
    perform vault.create_secret(s,'bonebrake_domain_onboarding_worker_secret','Bonebrake domain onboarding scheduler credential',null);
  end if;
end $$;

create or replace function public.phase14_queue_production_when_domain_ready()
returns trigger language plpgsql security invoker set search_path=public,pg_temp as $$
declare v_release public.project_release_candidates%rowtype; v_name text;
begin
  if new.is_primary is true and new.status in ('verified','active') and new.ssl_status='ready'
     and (tg_op='INSERT' or old.status is distinct from new.status or old.ssl_status is distinct from new.ssl_status or old.is_primary is distinct from new.is_primary) then
    update public.projects set domain_status='ready',updated_at=now() where id=new.project_id and domain_status is distinct from 'ready';
    select * into v_release from public.project_release_candidates
      where project_id=new.project_id and status='release_ready'
      order by release_ready_at desc nulls last,created_at desc limit 1;
    if found then
      select client_name into v_name from public.projects where id=new.project_id;
      if not exists(select 1 from public.automation_actions where action_type='deploy_paid_project_production' and entity_type='project' and entity_id=new.project_id and status in ('pending','approved','executing')) then
        insert into public.automation_actions(action_type,entity_type,entity_id,title,summary,risk_level,status,proposed_by,payload)
        values('deploy_paid_project_production','project',new.project_id,'Deploy production for '||coalesce(v_name,'paid client'),'The approved release now has a verified SSL-ready primary domain. Production still requires explicit owner approval and the Production Deployment switch.','approval','pending','domain_gate',jsonb_build_object('project_id',new.project_id,'release_candidate_id',v_release.id,'domain_id',new.id,'hostname',new.hostname,'external_effect','activate_verified_production_domain','requires_production_switch',true));
      end if;
      update public.projects set next_action='await_production_deployment',updated_at=now() where id=new.project_id and status<>'complete';
    end if;
  end if;
  return new;
end $$;
revoke all on function public.phase14_queue_production_when_domain_ready() from public,anon,authenticated;
drop trigger if exists phase14_queue_production_when_domain_ready on public.project_site_domains;
create trigger phase14_queue_production_when_domain_ready after insert or update of status,ssl_status,is_primary on public.project_site_domains for each row execute function public.phase14_queue_production_when_domain_ready();